### ISSUE TITLE
can you put this on npm?

### ISSUE THREAD

**Issue by bdougie** [anglibs/angular-location-update#1]

**Comment by garmoshka-mo** [comment]
never published to npm, and quite busy nowadays 
if someone know how to do it fast - you're welcome to join - i'll give all permissions to project if any needed

**Comment by bdougie** [comment]
The process is simple and have free time today and tomorrow. If you grant me access to the repo so I can clone your push up to npm

**Comment by bdougie** [comment]
Thanks so much, if you get a chance following these instructions in the command or create an accounton npm. I want to make sure you get credit for the library and add you as a collaborator on npm.

I will also update the readme to have npm instructions. Thanks again! 

```
npm set init.author.name "Your Name"
npm set init.author.email "you@example.com"
npm set init.author.url "http://yourblog.com"

npm adduser
```

**Comment by garmoshka-mo** [comment]
thanx forinstructions, done

Username: garmoshka-mo
